CREATE TABLE HUGO.TEST_DETALLE_FACTURA
(
  ID_DETALLE_FACTURA  NUMBER(19)                NOT NULL,
  IMPORTE             NUMBER(19,2),
  PLATO               VARCHAR2(255 CHAR),
  ID_COCINERO         NUMBER(19),
  ID_FACTURA          NUMBER(19)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE HUGO.TEST_DETALLE_FACTURA ADD (
  PRIMARY KEY
  (ID_DETALLE_FACTURA)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ENABLE VALIDATE);

ALTER TABLE HUGO.TEST_DETALLE_FACTURA ADD (
  CONSTRAINT FKGCCPHHVXGYABSF6SVJOQB35NB 
  FOREIGN KEY (ID_COCINERO) 
  REFERENCES HUGO.TEST_COCINEROS (ID_COCINERO)
  ENABLE VALIDATE,
  CONSTRAINT FKOGPXMLJMMMGJ0TOSPKO9T6I66 
  FOREIGN KEY (ID_FACTURA) 
  REFERENCES HUGO.TEST_FACTURAS (ID_FACTURA)
  ENABLE VALIDATE);
