CREATE TABLE HUGO.TEST_FACTURAS
(
  ID_FACTURA     NUMBER(19)                     NOT NULL,
  FECHA_FACTURA  TIMESTAMP(6),
  ID_CAMARERO    NUMBER(19),
  ID_CLIENTE     NUMBER(19),
  ID_MESA        NUMBER(19)
)
TABLESPACE USERS
RESULT_CACHE (MODE DEFAULT)
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
            FLASH_CACHE      DEFAULT
            CELL_FLASH_CACHE DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


ALTER TABLE HUGO.TEST_FACTURAS ADD (
  PRIMARY KEY
  (ID_FACTURA)
  USING INDEX
    TABLESPACE USERS
    PCTFREE    10
    INITRANS   2
    MAXTRANS   255
    STORAGE    (
                INITIAL          64K
                NEXT             1M
                MINEXTENTS       1
                MAXEXTENTS       UNLIMITED
                PCTINCREASE      0
                BUFFER_POOL      DEFAULT
                FLASH_CACHE      DEFAULT
                CELL_FLASH_CACHE DEFAULT
               )
  ENABLE VALIDATE);

ALTER TABLE HUGO.TEST_FACTURAS ADD (
  CONSTRAINT FK7HYH57B7YUIB2S1FOAJSF0KJJ 
  FOREIGN KEY (ID_CLIENTE) 
  REFERENCES HUGO.TEST_CLIENTES (ID_CLIENTE)
  ENABLE VALIDATE,
  CONSTRAINT FK81C2P27E5NKTKD1QSO66LPYJE 
  FOREIGN KEY (ID_MESA) 
  REFERENCES HUGO.TEST_MESAS (ID_MESA)
  ENABLE VALIDATE,
  CONSTRAINT FKK5M5IQ8RJQAVL1YUJLGFHGW7H 
  FOREIGN KEY (ID_CAMARERO) 
  REFERENCES HUGO.TEST_CAMAREROS (ID_CAMARERO)
  ENABLE VALIDATE);
